pipeline:
  name: test-fastlane-build
  identifier: testfastlanebuild
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Validate Documentation
        identifier: Validate_Documentation
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Setup build
                  identifier: Setup_build
                  spec:
                    connectorRef: harnessnew
                    image: fastlanetools/ci:0.3.0
                    shell: Sh
                    command: |-
                      #!/bin/bash -eo pipefail
                      gem update --system
              - step:
                  type: Run
                  name: Bundle install
                  identifier: Bundle_install
                  spec:
                    connectorRef: harnessnew
                    image: fastlanetools/ci:0.3.0
                    shell: Sh
                    command: |-
                      #!/bin/bash -eo pipefail
                      gem install bundler -v $(cat Gemfile.lock | tail -1 | tr -d " ")
                      bundle config set --local path .bundle
                      bundle check || bundle install --jobs=4 --retry=3
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: fastlane
        build: <+input>
