pipeline:
  name: test-fastlane-build
  identifier: testfastlanebuild
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  stages:
    - parallel:
        - stage:
            name: Validate Documentation
            identifier: Validate_Documentation
            type: CI
            spec:
              cloneCodebase: true
              execution:
                steps:
                  - step:
                      type: Run
                      name: Setup build
                      identifier: Setup_build
                      spec:
                        connectorRef: harnessnew
                        image: fastlanetools/ci:0.3.0
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          sudo gem update --system
                  - step:
                      type: Run
                      name: Bundle install
                      identifier: Bundle_install
                      spec:
                        connectorRef: harnessnew
                        image: fastlanetools/ci:0.3.0
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          sudo gem install bundler -v 2.3.14
                          sudo bundle config set --local path .bundle
                          sudo bundle check || bundle install --jobs=4 --retry=3
                  - step:
                      type: Run
                      name: Run_3
                      identifier: Run_3
                      spec:
                        connectorRef: harnessnew
                        image: fastlanetools/ci:0.3.0
                        shell: Sh
                        command: |
                          #!/bin/bash -eo pipefail

                          sudo gem install bundler -v 2.3.14
                          sudo bundle config set --local path .bundle
                          sudo bundle exec fastlane validate_docs
                      when:
                        stageStatus: All
                      failureStrategies: []
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
        - stage:
            name: Modules load up tests
            identifier: Modules_load_up_tests
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              execution:
                steps:
                  - step:
                      type: Run
                      name: Setup build
                      identifier: Setup_build
                      spec:
                        connectorRef: harnessnew
                        image: circleci/ruby:2.6
                        shell: Sh
                        command: |-
                          #!/bin/bash --login -eo pipefail
                          gem install $(echo $(gem build fastlane.gemspec) | sed 's/.*File: //')
                  - step:
                      type: Run
                      name: Run tests
                      identifier: Run_tests
                      spec:
                        connectorRef: harnessnew
                        image: circleci/ruby:2.6
                        shell: Sh
                        command: |-
                          #!/bin/bash --login -eo pipefail
                          /bin/bash ./test_modules/run_tests.sh
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
        - stage:
            name: Lint source code
            identifier: Lint_source_code
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: bundle install
                      identifier: bundle_install
                      spec:
                        connectorRef: harnessnew
                        image: circleci/ruby:2.6
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          gem install bundler -v $(cat Gemfile.lock | tail -1 | tr -d " ")
                          bundle config set --local path .bundle
                          bundle check || bundle install --jobs=4 --retry=3
                  - step:
                      type: Run
                      name: lint test
                      identifier: lint_test
                      spec:
                        connectorRef: harnessnew
                        image: circleci/ruby:2.6
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          bundle exec fastlane lint_source
        - stage:
            name: Execute tests on Ubuntu
            identifier: Execute_tests_on_Ubuntu
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: Setup Build
                      identifier: Setup_Build
                      spec:
                        connectorRef: harnessnew
                        image: fastlanetools/ci:0.3.0
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          mkdir -p ~/test-reports
                        envVariables:
                          LC_ALL: C.UTF-8
                          LANG: C.UTF-8
                          FASTLANE_ITUNES_TRANSPORTER_PATH: .bundle
                  - step:
                      type: Run
                      name: Bundle install
                      identifier: Bundle_install
                      spec:
                        connectorRef: harnessnew
                        image: fastlanetools/ci:0.3.0
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          sudo gem install bundler -v 2.3.14
                          sudo bundle config set --local path .bundle
                          sudo bundle check 

                          sudo bundle update fastlane
                          sudo bundle exec fastlane execute_tests
                        envVariables:
                          LC_ALL: C.UTF-8
                          LANG: C.UTF-8
                          FASTLANE_ITUNES_TRANSPORTER_PATH: .bundle
                  - step:
                      type: Run
                      name: Check PR metadata
                      identifier: Check_PR_metadata
                      spec:
                        connectorRef: harnessnew
                        image: fastlanetools/ci:0.3.0
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          sudo bundle exec danger || echo "danger failed"
                        envVariables:
                          LC_ALL: C.UTF-8
                          LANG: C.UTF-8
                          FASTLANE_ITUNES_TRANSPORTER_PATH: .bundle
                      when:
                        stageStatus: All
                      failureStrategies: []
                  - step:
                      type: Run
                      name: Fastlane tests
                      identifier: Fastlane_tests
                      spec:
                        connectorRef: harnessnew
                        image: fastlanetools/ci:0.3.0
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          sudo gem install bundler:2.3.14
                          sudo bundle install
                          sudo bundle update fastlane
                          sudo bundle exec fastlane execute_tests
                        envVariables:
                          LC_ALL: C.UTF-8
                          LANG: C.UTF-8
                          FASTLANE_ITUNES_TRANSPORTER_PATH: .bundle
                      when:
                        stageStatus: All
                      failureStrategies: []
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: fastlane
        build: <+input>
  allowStageExecutions: true
